/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by `next dev`/`next build` and should not be
// edited by hand — committed here only so the repo type-checks before the
// first `next dev` run regenerates it.
